### ISSUE TITLE
Readme's link is broken

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/mvdXML#10]
Main Readme links to http://www.buildingsmart-tech.org/specifications/mvd-overview/mvd-overview-summary - broken

**Comment by MatthiasWeise** [comment]
I checked the XSD with https://www.utilities-online.info/xsdvalidation and missed this issue. Does it work when you change the order as proposed (<xs:attribute ...> after the <xs:sequence ..>)?

**Comment by MatthiasWeise** [comment]
`			<xs:element name="Constraints" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="Constraint">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="mvd:RuleMessage" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
								<xs:attribute name="Expression" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>`

**Comment by pjanck** [comment]
Yes, after I change the order, it works (except for #9, of course).
