### ISSUE TITLE
mvdXML 1.2 comparing literals 

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/mvdXML#16]
Reading mvdXML 1.2 documentation, section 7.2.5

```
<TemplateRule Parameters="PropertySetName[Value]='Pset_MaterialCommon' and SimplePropertyName[Value]='MassDensity' and NominalValue[Value] > '0.0'"/>
```

I believe that it should read `NominalValue[Value] > 0.0`, i.e. comparing to a real literal. If that is the case, correct all occurances.

**Comment by MatthiasWeise** [comment]
Yes, that should be a real literal. It will be fixed with the next upload.
