### ISSUE TITLE
mvdXML 1.2 editorial errors in the documentation

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/mvdXML#18]
Reading mvdXML 1.2 documentation:

1. table of content: page number for section 7.2.6 is erroneous
2. section 0: inconsistent end of sentence punctuation for the bullet point
3. section 0, bullet point 3: typo *funtionality*
4. section 0, bullet point 5: there is a reference to `0` - probably erroneous
5. section 0: the reference to *chapter 4* includes the word *chapter*, while the references to subsections *7.2.6*, ..., do not. I'd propose to also include the word *section*  for these.
6. section 4, ANTLR part: typo *Mordernized*

I did not read through the whole document yet, so this doesn't mean that I've cought them all.

**Comment by MatthiasWeise** [comment]
Thanks for this feedback. PDF documentation is updated and includes last changes of the rule grammar.
