### ISSUE TITLE
Proposal: SELF_SIZE (or similar)

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/mvdXML#27]
### Idea

An idea occurred to me when thinking about the `SELF_TYPE` token and where else a `SELF` reference could be useful. I could imagine the following scenario during certification (I can hardly imagine a scenario outside of that):

1. The file should contain one and only one element of type `IFCANNOTATION`. 

*How to specify this in the current state of the standard?* If there is a solution, ignore the following proposal.

### Proposal

Introduce a `SELF_SIZE` token to be used in the parameter strings. Usage example for the above statement (taking the example 7.2.3 from the documentation as a basis):

    <ConceptRoot uuid="2aa33a62-6f0e-4d03-9f00-ba1796c62f1e" name="Ensure one IfcAnnotation" applicableRootEntity="IfcAnnotation">
      <Concepts>
        <Concept uuid="5fc09487-885f-4185-98e2-cb3ba2386087" name="Only one occurrance">
          <Template ref="6d70aadb-bd68-41b3-8b0f-0b56c5c09e86"/>
          <TemplateRule Parameters="SELF_SIZE=1"/>
        </Concept>
      </Concepts>
    </ConceptRoot>

**Comment by arch1501** [comment]
Please check the element applicability, there you will find the attributes minOccurence and maxOccurence.

**Comment by pjanck** [comment]
Thank you for the fast response! I see that this is already possible with the existing schema - I withdraw my proposal.
