### ISSUE TITLE
Why are these two attributes as "xs:list"?

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/mvdXML#6]
https://github.com/buildingSMART/mvdXML/blob/ec725f1aeade53926a02b4185d5073782bb03210/mvdXML1.1/xsd/mvdXML_V1-1_draft.xsd#L138-L151

**Comment by MatthiasWeise** [comment]
A ConceptTemplate could be applicable for more than one IFC schema and entity. In practice we are using only one schema and one entity, which is also recommended by the documentation. Multiple schema support might be of interest if we are going to standardize the ConceptTemplates with a stable UUID.

**Comment by pjanck** [comment]
Right. That explains it - thank you for the quick response!
